build:
  environment:
    node:
      version: 16.15.0
  nodes:
    analysis:
      tests:
        override:
          - yarn lint
          - yarn lint:css
          - js-scrutinizer-run
          - command: "CI=true yarn test:coverage"
            coverage:
              file: "coverage/clover.xml"
              format: "clover"
      cache:
        directories:
          - .next/cache
  tests:
    before:
      - command: yarn build
        idle_timeout: 5000
